first commit, md proposed metrics v.1 + src file v.1
KrisMTLA/ae-capstone-ksand pull request #1
Opened 2022-05-06 13:37 UTC by KrisMTLA

Initial thoughts on proposed Metrics for each of the 5 departments

v.1 of my src_ecommerce.yml file

2022-05-09 20:01 UTC, JFrackson requested changes
Quick comment about the .DS_Store file: this is an Apple only config that we can ignore when working on projects. Adding .DS_Store to your gitignore and then deleting it here should do the trick. Out of curiosity, which MacOS version are you running? 

Apart from that, looks pretty good and includes lots of metrics already but with minimal detail. Don't worry too much about providing detail for all of them, but as per the comments, try structuring 3-4 of them with a name, description, and visualization example. This will help for one of the sections later on!

2022-05-09 20:01 UTC, JFrackson commented on capstone/models/example/schema.yml
>  version: 2
this too can be deleted!

2022-05-09 20:01 UTC, JFrackson commented on capstone/proposed_metrics.md
> +fct_order_items > count of orders by product - view overtime with timeframe flexiblity, total sales by product
This is good, but could be more precise (and the precision will help when it comes to making a visualization later). Count of orders is the metric and then product is a grouping dimension, but what exactly do you mean by timeframe? Product will care more about when something was purchased whereas logistics might be interested in delivery lifecycle and delivery dates. 

Adding lots of detail isn't super necessary, but it will help us plan things out in a lot more detail. Here's the metric example from the hint in the capstone:

```
### **Product:**

**Metric:** Amount Sold

**Definition:** `sum(price) as amount_sold`; this can be grouped by things like product category but doesn’t need to be filtered by any particular field.

**Visualization:** Weekly Amount Sold by Product Category; stacked bar chart where the x-axis is `orders.purchased_timestamp` , the y-axis is `sum(order_items.price)` , and the bar groupings are defined by `products.product_category_name` .
```

2022-05-09 20:01 UTC, JFrackson commented on capstone/proposed_metrics.md
> +fct_customers > count of orders, total spend, average spend, first order date, last order date, retention metrics (percent of customers who made 2nd order, Nth order)
These are great too: this version is pitching them as dimensionalized facts (facts that have been pushed to a dimension to be used as dimensional fields e.g. bucket customers by their average spend and then see their reviews for the past 6 months). 

Taken individually, these are also great metrics, and you can also start making more derivative metrics like using the first_order_date and last_order_date you can determine a customer's "age" at the time of purchase. 

Similarly, you can also calculate things like retention, but retention is a metric that exists not on a customer (bc that would just be true or false), but rather on a group of customers (e.g. customers who first purchased in 2017). 

For another challenge here, you could add a metric called 3-, 6-, 12- month retention and explain what you would group that by and how it would be precisely defined.

2022-05-09 20:01 UTC, JFrackson commented on capstone/proposed_metrics.md
> +fct_order_items > total freight value, average freight value
The other type of metric that's very common for something like logistics is a duration metric or time_to_x metric. How would you define a metric like that? E.g. time_to_deliver And how would you group and analyze it?

2022-05-10 12:32 UTC, KrisMTLA commented
> 

I am confused here, not sure where this 'DS_Store' file lives in the DBT project. Searched and I could not find it 

I have an M1 mac running macOS Montery 12.3.1

2022-05-10 12:34 UTC, KrisMTLA commented on capstone/models/example/schema.yml
>  version: 2
deleted the entire example folder along with this file

2022-05-11 20:01 UTC, JFrackson approved these changes
Looks great! Left two more comments but they're more informational. 

As for the DS_Store it's a hidden by default file type so it can be hard to figure out / work with. I think depending on how you set up git originally some setups auto-exclude these files while others don't. For the sake of this project, don't worry about it. Now that it's in the gitignore no more will be added at least

2022-05-11 20:01 UTC, JFrackson commented on capstone/proposed_metrics.md
> +**Metric:**  customer age
This is an interesting one: although you could be interested in knowing how the average or median age is changing, you're probably more likely to be interested in age as a dimension (e.g. count of customers distributed by age). Small point, and you say something similar below, but worth mentioning!

2022-05-11 20:01 UTC, JFrackson commented on capstone/proposed_metrics.md
> +**Visualization:** Average Customer Age by Product Category; Bar chart where the x-axis is `products.product_category_name`, the y-axis is `avg(customer_age)`.
So this viz uses it as a metric, but you could also imagine it being bucketed as a line pivot (which would be a dimensional usage of age)

2022-05-12 11:46 UTC, merged